### ISSUE TITLE
drop_z function not working

### ISSUE THREAD

**Issue by TerryLines** [TerryLines/gnssmapper#2]
The geo drop_z function does not recognise the geometry object. This is because it is pygeos based and needs data frame.geometry.array.data not frame.geometry

>>> gm.geo.drop_z(mymap)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/terry/GNSS/gnssmapper/gnssmapper/geo.py", line 205, in drop_z
    if pygeos.has_z(map_.geometry).any():
  File "/Users/terry/GNSS/gnssmapper/.venv/lib/python3.7/site-packages/pygeos/decorators.py", line 55, in wrapped
    return func(*args, **kwargs)
  File "/Users/terry/GNSS/gnssmapper/.venv/lib/python3.7/site-packages/pygeos/predicates.py", line 51, in has_z
    return lib.has_z(geometry, **kwargs)
  File "/Users/terry/GNSS/gnssmapper/.venv/lib/python3.7/site-packages/pandas/core/generic.py", line 1936, in __array_ufunc__
    return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
  File "/Users/terry/GNSS/gnssmapper/.venv/lib/python3.7/site-packages/pandas/core/arraylike.py", line 358, in array_ufunc
    result = getattr(ufunc, method)(*inputs, **kwargs)
TypeError: One of the arguments is of incorrect type. Please provide only Geometry objects.

**Comment by TerryLines** [comment]
fixed in version 0.0.1a5
